# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  batch: true
  branches:
    include:
      - 'main'

pr:
  branches:
    include:
      - 'main'

pool:
  vmImage: 'ubuntu-latest'

steps:
  - script: docker run --rm -v $(pwd):/work:ro -w /work tmaier/markdown-spellcheck:latest --report "**/*.md"
    displayName: 'Check Spelling'

  - script: shopt -s globstar; echo **/*.md | xargs -n1 docker run --rm -v $(pwd):/work:ro -w /work robertbeal/markdown-link-checker
    displayName: 'Check Links'

  - task: GitHubRelease@0
    displayName: 'Create Release'
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
    inputs:
      gitHubConnection: 'slawekzachcial'
      tag: $(Build.BuildNumber)

  - script: echo "Deploy website."
    displayName: 'Deploy'
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
