# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  batch: true
  branches:
    include:
      - 'main'

pr:
  branches:
    include:
      - 'main'

pool:
  vmImage: 'ubuntu-latest'

variables:
  isMain: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]

steps:
  - checkout: self
    persistCredentials: true

  - task: Bash@3
    inputs:
      filePath: pipeline.sh
      arguments: checkSpelling
    displayName: 'Check Spelling'

  - task: Bash@3
    inputs:
      filePath: pipeline.sh
      arguments: checkLinks
    displayName: 'Check Links'

  - script: |
      echo "##vso[task.setvariable variable=releaseVersion]$(./pipeline.sh getReleaseTag $(Build.SourceVersion))"
    displayName: 'Get Release Version'

  - task: GitHubRelease@0
    displayName: 'Create Release'
    condition: and(succeeded(), eq(variables.isMain, true), eq(variables.releaseVersion, ''))
    inputs:
      gitHubConnection: 'github.com_slawekzachcial'
      tag: $(Build.BuildNumber)
      tagSource: manual

  # `releaseVersion` either already has value coming from tag or is set to BuildNumber
  # so that proper commit message can be specified in gh-pages branch.
  - script: |
      echo "##vso[task.setvariable variable=releaseVersion]$(Build.BuildNumber)"
    displayName: 'Set Release Version'
    condition: and(succeeded(), eq(variables.isMain, true), eq(variables.releaseVersion, ''))

  - script: |
      echo "##vso[task.setvariable variable=shouldDeploy]$(./pipeline.sh shouldDeploy && echo True)"
    displayName: 'Should Deploy Pages?'
    condition: and(succeeded(), eq(variables.isMain, true))

  - task: Bash@3
    inputs:
      filePath: pipeline.sh
      arguments: deployPages $(Build.BuildNumber) $(releaseVersion)
    displayName: 'Deploy GitHub Pages'
    condition: and(succeeded(), eq(variables.isMain, true), eq(variables.shouldDeploy, true))
