# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  batch: true
  branches:
    include:
      - 'main'

pr:
  branches:
    include:
      - 'main'

pool:
  vmImage: 'ubuntu-latest'

variables:
  isMain: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]

steps:
  - script: docker run --rm -v $(pwd):/work:ro -w /work tmaier/markdown-spellcheck:latest --report "**/*.md"
    displayName: 'Check Spelling'

  - script: shopt -s globstar; echo **/*.md | xargs -n1 docker run --rm -v $(pwd):/work:ro -w /work robertbeal/markdown-link-checker
    displayName: 'Check Links'

  # Use yes/no value for the variable to avoid confusion with conversion between string and boolean
  - script: |
      echo "##vso[task.setvariable variable=isNewRelease]$(git describe --tags --exact-match HEAD &>/dev/null && echo no || echo yes)"
    displayName: 'Is New Release?'

  - task: GitHubRelease@0
    displayName: 'Create Release'
    condition: and(succeeded(), eq(variables.isMain, true), eq(variables.isNewRelease, 'yes'))
    inputs:
      gitHubConnection: 'github.com_slawekzachcial'
      tag: $(Build.BuildNumber)
      tagSource: manual

  - script: |
      git status && \
      git switch gh-pages \
      && git config user.email slawekzachcial.pipelines-azure@dev.azure.com \
      && git config user.name 'Azure Pipelines' \
      && git restore --source origin/main README.md \
      && git commit -am "Deploy new release" \
      && git push \
      && git switch -
    displayName: 'Deploy Release'
    condition: and(succeeded(), eq(variables.isMain, true))
